using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FF8WMScriptsReader
{
    class Scripts
    {
        public List<string> Names = new List<string>()
        {
            "Shumi village",
            "Chocobo (Shumi)",
            "Chocobo Forest (Trabia continent)",
            "Trabia Garden",
            "Chocobo Forest (Trabia continent 2)",
            "Chocobo Forest (Esthar)",
            "Tomb of the Unknown King",
            "Dollet",
            "Deling",
            "Galbadia Garden (Balamb Garden broke)",
            "LD2 Forest (Timber)",
            "Balamb",
            "Balamb Garden (Left side)",
            "Balamb Garden (Right side)",
            "Trabia Canyon",
            "Missile base",
            "Prison",
            "Timber",
            "Fisherman Horizon Ragnarok",
            "FH Ragnarok (triggers only by leaving Garden)",
            "FH via Garden",
            "Esthar train station",
            "Salt lake",
            "Lunatic Pandora Laboratory",
            "Winhill Front",
            "Esthar (With cutscene)",
            "Esthar (Car)",
            "Esthar (Car)",
            "Esthar (Car)",
            "Esthar Sorceress Memorial",
            "Lunar Gate",
            "Chocobo forest (Centra North-East)",
            "Tear's point",
            "Centra Ruins",
            "Edea's house",
            "Chocobo forest (near Edea's house)",
            "Chocobo forest (Centra south-east)",
            "Deep sea research",
            "Balamb",
            "Balamb Garden",
            "Fire cavern",
            "Disables entering locations",
            "Dollet vessel",
            "Balamb behind trigger",
            "Return to Balamb after Dollet",
            "Balamb Garden",
            "TextBox Get off car",
            "TextBox (Galbadian Soldier)",
            "TextBox (Galbadian Soldier) 2",
            "Garden Collide",
            "Enter Seed ship",
            "Rinoa taken by Esthar",
            "Enter Ragnarok",
            "Lunatic Pandora Assault",
            "Enter Lunatic Pandora",
            "Enter Lunar Crash Site",
            "Enter trigger disabled",
            "TextBox Selphie go to Missile Base",
            "How to drive",
            "Garden Controls",
            "How to ride a Chocobo",
            "Spaceship Controls",
            "TextBox Edea's house",
            "TextBox Edea's house 2",
            "Disables entering locations (vehicle too)",
            "Galbadia Train Station",
            "UFO ship flying by Encounter Statue",
            "UFO ship flying by Encounter Cow",
            "UFO ship flying by Encounter Sign",
            "UFO ship flying by Encounter Pyramid",
            "Winhill Square",
            "UFO guy Encounter",
            "UFO ship Encounter",
            "Obel Lake (Choice)",
            "Obel Lake (Choice)",
            "Obel Lake (Choice 2)",
            "Obel Lake (A black shado..)",
            "Obel Lake (The rock skipped twi...)",
            "Obel Lake (Hello human what a...)",
            "Obel Lake (There's something lar...)",
            "Obel Lake (Thanks for speak...)",
            "Obel Lake (Can you do me a fav..)",
            "Obel Lake ....",
            "Obel Lake (Please...)",
            "Obel Lake (Mr. Monkey should be...)",
            "Obel Lake (Mr. Monkey should..)",
            "Obel Lake (What a beautiful day)",
            "Obel lake (Relayed the whereab...)",
            "Obel Lake (Thank you!)",
            "Obel lake (At the beach in Balamb, some...)",
            "Obel lake (You'll find something on an island..)",
            "Obel lake (There's also something on top..)",
            "Obel Lake (Take a break...)",
            "Obel Lake (Take some time off..)",
            "Obel Lake (I bet it's a wond...)",
            "TextBox (I wonder what it means)",
            "TextBox Obel Lake",
            "TextBox Obel Lake",
            "TextBox Obel Lake (I wonder what it means)",
            "Obel Lake",
            "[S T S L R M]",
            "Obel Lake I wonder what it means",
            "Disables enter triggers (vehicle too)",
            "You suck!",
            "The monkey disappeared",
            "The monkey told you off",
            "Monkey threw a rock",
            "Upon inspecting the rock",
            "[ something ]",
            "There is a stone pillar",
            "Continuing the text",
            "Continuing the text",
            "There are many multicolored",
            "Blue faced rock",
            "Blue faced rock",
            "......What's this!?",
            "Found Three Stars!",
            "....What's this!?",
            "Dollet mission Vessel (working)",
            "Dollet mission Vessel (working)",
            "You found a piece of rock",
            "Continuing previous text",
            "Continuing previous text",
            "Choice A bird is warming",
            "???",
            "Piece of rock",
            "Continuing previous text",
            "Continuing previous text",
            "Continuing previous text",
            "Continuing previous text",
            "Continuing previous text",
            "Continuing previous text",
            "Enter Deling",
            "Enter Deling",
        };
    }
}
